"$schema" = "https://starship.rs/config-schema.json"

add_newline = true
format = """
 \
$nix_shell\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$all"""

[character]
success_symbol = "[ 󰄾](bold green)"
error_symbol = "[ 󱎘](bold red)"

[cmd_duration]
min_time = 0
style = "#a5a5a5"
format = "[|](bright-black) [󰅐  $duration]($style) "

[battery]
disabled = true

[directory]
truncate_to_repo = false
read_only = "  "
read_only_style = "yellow"

[nix_shell]
format = "$symbol "
symbol = "[ ](cyan) [$name](cyan italic) [|](bright-black)"

[git_branch]
style = "yellow"
symbol = "[󰊢  ](#f54c27)"
format = "[|](bright-black) [$symbol$branch(:$remote_branch)]($style)"

[git_status]
format = "( $all_status$ahead_behind) "

conflicted = " [ ](bold red)"
ahead = " [󰳢 ](green)"
behind = " [󰳜 ](green)"
diverged = " [ ](yellow)"
untracked = " [ ](blue)"
stashed = " [ ](blue dimmed)"
up_to_date = ""
modified = " [ ](yellow)"
staged = " [ ](green)"
renamed = " [ ](yellow)"
deleted = " [ ](red dimmed)"

[gcloud]
symbol = "[](cyan)"
format = "[|](bright-black) [$symbol](blue) [$project](cyan bold) [$account(@$domain )](blue dimmed)"

[terraform]
disabled = true

[lua]
disabled = true

[nodejs]
symbol = "  "
style = "yellow"
format = "[|](bright-black) [$symbol($version )]($style)"

[golang]
symbol = "[ﳑ ](#79d4fd) "
style = "cyan dimmed"
format = "[|](bright-black) [$symbol($version )]($style)"

[rust]
style = "red"
format = "[|](bright-black) [$symbol($version )]($style)"

[buf]
style = "blue"
format = "[|](bright-black) [$symbol ($version )]($style)"

[package]
style = "208"
symbol = "  "
format = "[|](bright-black) [$symbol($version) ]($style)"

[kubernetes]
disabled = false
symbol = "󱃾  "
style = "cyan"
format = "[|](bright-black) [$symbol$context ]($style)"

[kubernetes.context_aliases]
"gke_.*_(?P<var_cluster>[\\w-]+)" = "gke-$var_cluster"
"arn:aws:eks:(?P<var_region>[\\w-]+):(?P<var_account>[\\w-]+):cluster/(?P<var_cluster>[\\w-]+)" = "eks:$var_cluster"

[c]
format = "[|](bright-black) [$symbol($version(-$name) )]($style)"
style = "149"

[cmake]
format = "[|](bright-black) [$symbol($version )]($style)"

[aws]
disabled = true
symbol = "  "
style = "yellow"
format = "[|](bright-black) [$symbol](yellow)[($profile )($region )(\\[$duration\\] )]($style)"

[python]
format = "[|](bright-black) [${symbol}${pyenv_prefix}(${version} )(\\($virtualenv\\) )]($style)"
symbol = " "

[zig]
format = "[|](bright-black) [$symbol($version )]($style)"
symbol = " "

[vagrant]
symbol = "  "
format = "[|](bright-black) [$symbol($version )]($style)"
