return {
  {
    "nvim-treesitter/nvim-treesitter",
    version = false,
    build = ":TSUpdate",
    event = { "BufReadPost", "BufNewFile" },
    dependencies = {
      "windwp/nvim-ts-autotag",
    },
    opts = {
      highlight = { enable = true },
      indent = { enable = true },
      autotag = { enable = true },
      context_commentstring = { enable = true, enable_autocmd = false },
      ensure_installed = {
        "bash",
        "c",
        "cpp",
        "comment",
        "css",
        "cue",
        "dockerfile",
        "dot",
        "elixir",
        "git_rebase",
        "gitcommit",
        "gitignore",
        "gitattributes",
        "go",
        "gomod",
        "gosum",
        "gowork",
        "graphql",
        "hcl",
        "heex",
        "http",
        "ini",
        "java",
        "javascript",
        "jq",
        "jsdoc",
        "json",
        "jsonc",
        "json5",
        "kotlin",
        "lua",
        "luadoc",
        "make",
        "markdown",
        "markdown_inline",
        "nix",
        "rasi",
        "regex",
        "rust",
        "sql",
        "svelte",
        "terraform",
        "toml",
        "tsx",
        "typescript",
        "vim",
        "vue",
        "yaml",
        "yuck",
        "zig",
      },
    },
    config = function(_, opts)
      require("nvim-treesitter.configs").setup(opts)
    end,
  },

  { "NoahTheDuke/vim-just", ft = "just" },
  { "JoosepAlviste/nvim-ts-context-commentstring", lazy = true },
}
