#!/usr/bin/env bash
set -eo pipefail

if [[ -f "$HOME/.config/.flake-nvim-lock" ]]; then
  echo -e "\e[1;31merror:\e[0m already editing neovim config"
  exit 1
fi

rm -rf ~/.config/nvim
cp -r ~/.flake/config/nvim ~/.config
touch ~/.config/.flake-nvim-lock