#!/usr/bin/env bash
set -eo pipefail

if [[ ! -f "$HOME/.config/.flake-nvim-lock" ]]; then
  echo -e "\e[1;31merror:\e[0m not currently editing neovim config"
  exit 1
fi

rm -r ~/.flake/config/nvim
cp -rf ~/.config/nvim ~/.flake/config
rm -rf ~/.config/nvim
rm ~/.config/.flake-nvim-lock