update_check = false
db_path = "/tmplocal/atuin-db/history.db"
sync_address = "https://atuin.happens.lol"
style = "compact"
invert = true
show_preview = true
show_help = false
inline_height = 10
number_jump_modifier = "ctrl"
