update_check = false
sync_address = "https://atuin.happens.lol"
key_path = "/home/happens/.local/share/atuin-store/key"
session_path = "/home/happens/.local/share/atuin-store/session"
style = "compact"
invert = true
show_preview = true
show_help = false
inline_height = 10
number_jump_modifier = "ctrl"
